// Code generated by musgen-go. DO NOT EDIT.

package another

import (
	dts "github.com/mus-format/dts-go"
	"github.com/mus-format/mus-go/varint"
)

var MyAwesomeIntMUS = myAwesomeIntMUS{}

type myAwesomeIntMUS struct{}

func (s myAwesomeIntMUS) Marshal(v MyInt, bs []byte) (n int) {
	return varint.Int.Marshal(int(v), bs)
}

func (s myAwesomeIntMUS) Unmarshal(bs []byte) (v MyInt, n int, err error) {
	tmp, n, err := varint.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	v = MyInt(tmp)
	return
}

func (s myAwesomeIntMUS) Size(v MyInt) (size int) {
	return varint.Int.Size(int(v))
}

func (s myAwesomeIntMUS) Skip(bs []byte) (n int, err error) {
	return varint.Int.Skip(bs)
}

var MyAwesomeIntDTS = dts.New[MyInt](MyAwesomeIntDTM, MyAwesomeIntMUS)
