// Code generated by musgen-go. DO NOT EDIT.

package testdata

import (
	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/varint"
)

var (
	ptrDGwUeg46vIKW3NFIBKm9aAΞΞ   = ord.NewPtrSer[[]int](slicevpupCiHq038GXCphsoΔMCgΞΞ)
	ptrpΣgQmFy55dhQfwe2RxdJ8gΞΞ   = ord.NewPtrSer[MyStruct](MyStructMUS)
	ptrvYOBjyIWKgAJtJCLcOb9qwΞΞ   = ord.NewPtrSer[int](varint.Int)
	slicevpupCiHq038GXCphsoΔMCgΞΞ = ord.NewSliceSer[int](varint.Int)
)

var MyIntPtrMUS = myIntPtrMUS{}

type myIntPtrMUS struct{}

func (s myIntPtrMUS) Marshal(v MyIntPtr, bs []byte) (n int) {
	return ptrvYOBjyIWKgAJtJCLcOb9qwΞΞ.Marshal((*int)(v), bs)
}

func (s myIntPtrMUS) Unmarshal(bs []byte) (v MyIntPtr, n int, err error) {
	tmp, n, err := ptrvYOBjyIWKgAJtJCLcOb9qwΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = MyIntPtr(tmp)
	return
}

func (s myIntPtrMUS) Size(v MyIntPtr) (size int) {
	return ptrvYOBjyIWKgAJtJCLcOb9qwΞΞ.Size((*int)(v))
}

func (s myIntPtrMUS) Skip(bs []byte) (n int, err error) {
	return ptrvYOBjyIWKgAJtJCLcOb9qwΞΞ.Skip(bs)
}

var MySlicePtrMUS = mySlicePtrMUS{}

type mySlicePtrMUS struct{}

func (s mySlicePtrMUS) Marshal(v MySlicePtr, bs []byte) (n int) {
	return ptrDGwUeg46vIKW3NFIBKm9aAΞΞ.Marshal((*[]int)(v), bs)
}

func (s mySlicePtrMUS) Unmarshal(bs []byte) (v MySlicePtr, n int, err error) {
	tmp, n, err := ptrDGwUeg46vIKW3NFIBKm9aAΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = MySlicePtr(tmp)
	return
}

func (s mySlicePtrMUS) Size(v MySlicePtr) (size int) {
	return ptrDGwUeg46vIKW3NFIBKm9aAΞΞ.Size((*[]int)(v))
}

func (s mySlicePtrMUS) Skip(bs []byte) (n int, err error) {
	return ptrDGwUeg46vIKW3NFIBKm9aAΞΞ.Skip(bs)
}

var MyStructMUS = myStructMUS{}

type myStructMUS struct{}

func (s myStructMUS) Marshal(v MyStruct, bs []byte) (n int) {
	return
}

func (s myStructMUS) Unmarshal(bs []byte) (v MyStruct, n int, err error) {
	return
}

func (s myStructMUS) Size(v MyStruct) (size int) {
	return
}

func (s myStructMUS) Skip(bs []byte) (n int, err error) {
	return
}

var MyStructPtrMUS = myStructPtrMUS{}

type myStructPtrMUS struct{}

func (s myStructPtrMUS) Marshal(v MyStructPtr, bs []byte) (n int) {
	return ptrpΣgQmFy55dhQfwe2RxdJ8gΞΞ.Marshal((*MyStruct)(v), bs)
}

func (s myStructPtrMUS) Unmarshal(bs []byte) (v MyStructPtr, n int, err error) {
	tmp, n, err := ptrpΣgQmFy55dhQfwe2RxdJ8gΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = MyStructPtr(tmp)
	return
}

func (s myStructPtrMUS) Size(v MyStructPtr) (size int) {
	return ptrpΣgQmFy55dhQfwe2RxdJ8gΞΞ.Size((*MyStruct)(v))
}

func (s myStructPtrMUS) Skip(bs []byte) (n int, err error) {
	return ptrpΣgQmFy55dhQfwe2RxdJ8gΞΞ.Skip(bs)
}
