// Code generated by musgen-go. DO NOT EDIT.\n\npackage

package pkg1

import (
	dts "github.com/mus-format/mus-stream-dts-go"
	muss "github.com/mus-format/mus-stream-go"
)

func MarshalStreamInterfaceImpl1MUS(v InterfaceImpl1, w muss.Writer) (n int, err error) {
	return
}

func UnmarshalStreamInterfaceImpl1MUS(r muss.Reader) (v InterfaceImpl1, n int, err error) {
	return
}

func SizeStreamInterfaceImpl1MUS(v InterfaceImpl1) (size int) {
	return
}

func SkipStreamInterfaceImpl1MUS(r muss.Reader) (n int, err error) {
	return
}

var StreamInterfaceImpl1DTS = dts.New[InterfaceImpl1](InterfaceImpl1DTM,
	muss.MarshallerFn[InterfaceImpl1](MarshalStreamInterfaceImpl1MUS),
	muss.UnmarshallerFn[InterfaceImpl1](UnmarshalStreamInterfaceImpl1MUS),
	muss.SizerFn[InterfaceImpl1](SizeStreamInterfaceImpl1MUS),
	muss.SkipperFn(SkipStreamInterfaceImpl1MUS))

func MarshalStreamInterfaceImpl2MUS(v InterfaceImpl2, w muss.Writer) (n int, err error) {
	return
}

func UnmarshalStreamInterfaceImpl2MUS(r muss.Reader) (v InterfaceImpl2, n int, err error) {
	return
}

func SizeStreamInterfaceImpl2MUS(v InterfaceImpl2) (size int) {
	return
}

func SkipStreamInterfaceImpl2MUS(r muss.Reader) (n int, err error) {
	return
}

var StreamInterfaceImpl2DTS = dts.New[InterfaceImpl2](InterfaceImpl2DTM,
	muss.MarshallerFn[InterfaceImpl2](MarshalStreamInterfaceImpl2MUS),
	muss.UnmarshallerFn[InterfaceImpl2](UnmarshalStreamInterfaceImpl2MUS),
	muss.SizerFn[InterfaceImpl2](SizeStreamInterfaceImpl2MUS),
	muss.SkipperFn(SkipStreamInterfaceImpl2MUS))
