// Code generated by musgen-go. DO NOT EDIT.\n\npackage

package pkg1

import (
	dts "github.com/mus-format/mus-dts-go"
	"github.com/mus-format/mus-go"
)

func MarshalUnsafeInterfaceImpl1MUS(v InterfaceImpl1, bs []byte) (n int) {
	return
}

func UnmarshalUnsafeInterfaceImpl1MUS(bs []byte) (v InterfaceImpl1, n int, err error) {
	return
}

func SizeUnsafeInterfaceImpl1MUS(v InterfaceImpl1) (size int) {
	return
}

func SkipUnsafeInterfaceImpl1MUS(bs []byte) (n int, err error) {
	return
}

var UnsafeInterfaceImpl1DTS = dts.New[InterfaceImpl1](InterfaceImpl1DTM,
	mus.MarshallerFn[InterfaceImpl1](MarshalUnsafeInterfaceImpl1MUS),
	mus.UnmarshallerFn[InterfaceImpl1](UnmarshalUnsafeInterfaceImpl1MUS),
	mus.SizerFn[InterfaceImpl1](SizeUnsafeInterfaceImpl1MUS),
	mus.SkipperFn(SkipUnsafeInterfaceImpl1MUS))

func MarshalUnsafeInterfaceImpl2MUS(v InterfaceImpl2, bs []byte) (n int) {
	return
}

func UnmarshalUnsafeInterfaceImpl2MUS(bs []byte) (v InterfaceImpl2, n int, err error) {
	return
}

func SizeUnsafeInterfaceImpl2MUS(v InterfaceImpl2) (size int) {
	return
}

func SkipUnsafeInterfaceImpl2MUS(bs []byte) (n int, err error) {
	return
}

var UnsafeInterfaceImpl2DTS = dts.New[InterfaceImpl2](InterfaceImpl2DTM,
	mus.MarshallerFn[InterfaceImpl2](MarshalUnsafeInterfaceImpl2MUS),
	mus.UnmarshallerFn[InterfaceImpl2](UnmarshalUnsafeInterfaceImpl2MUS),
	mus.SizerFn[InterfaceImpl2](SizeUnsafeInterfaceImpl2MUS),
	mus.SkipperFn(SkipUnsafeInterfaceImpl2MUS))
