// Code generated by musgen-go. DO NOT EDIT.

package testdata

import (
	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/unsafe"
	struct_testdata "github.com/mus-format/musgen-go/testdata/struct"
)

var (
	arrayΣvrFYO2uuK77BSwd06iBygΞΞ = ord.NewArraySer[[3]int, int](unsafe.Int)
	map71wXjOfIxEib3Yt8SxUdDgΞΞ   = ord.NewMapSer[float32, map[struct_testdata.MyInt][]struct_testdata.MyStruct](unsafe.Float32, map9n1nfMΔXOhdb88iΔΔcscXwΞΞ)
	map9n1nfMΔXOhdb88iΔΔcscXwΞΞ   = ord.NewMapSer[struct_testdata.MyInt, []struct_testdata.MyStruct](MyIntMUS, sliceZJwnVgvHlXXapX34kEBjygΞΞ)
	ptr0UddYOKdSqL09vDtrQX5nQΞΞ   = ord.NewPtrSer[string](ord.String)
	ptrUT3ΔQ8KtGkzUdPF4EjzKUAΞΞ   = ord.NewPtrSer[[3]int](arrayΣvrFYO2uuK77BSwd06iBygΞΞ)
	ptrjoB7csTrtA9B1JLZgTz6UAΞΞ   = ord.NewPtrSer[struct_testdata.MyStruct](MyStructMUS)
	sliceMopk90PBNClFtz2Wc2tΣkQΞΞ = ord.NewSliceSer[string](ord.String)
	sliceZJwnVgvHlXXapX34kEBjygΞΞ = ord.NewSliceSer[struct_testdata.MyStruct](MyStructMUS)
)

var MyIntMUS = myIntMUS{}

type myIntMUS struct{}

func (s myIntMUS) Marshal(v struct_testdata.MyInt, bs []byte) (n int) {
	return unsafe.Int.Marshal(int(v), bs)
}

func (s myIntMUS) Unmarshal(bs []byte) (v struct_testdata.MyInt, n int, err error) {
	tmp, n, err := unsafe.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	v = struct_testdata.MyInt(tmp)
	return
}

func (s myIntMUS) Size(v struct_testdata.MyInt) (size int) {
	return unsafe.Int.Size(int(v))
}

func (s myIntMUS) Skip(bs []byte) (n int, err error) {
	return unsafe.Int.Skip(bs)
}

var MySliceMUS = mySliceMUS{}

type mySliceMUS struct{}

func (s mySliceMUS) Marshal(v struct_testdata.MySlice, bs []byte) (n int) {
	return sliceMopk90PBNClFtz2Wc2tΣkQΞΞ.Marshal([]string(v), bs)
}

func (s mySliceMUS) Unmarshal(bs []byte) (v struct_testdata.MySlice, n int, err error) {
	tmp, n, err := sliceMopk90PBNClFtz2Wc2tΣkQΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = struct_testdata.MySlice(tmp)
	return
}

func (s mySliceMUS) Size(v struct_testdata.MySlice) (size int) {
	return sliceMopk90PBNClFtz2Wc2tΣkQΞΞ.Size([]string(v))
}

func (s mySliceMUS) Skip(bs []byte) (n int, err error) {
	return sliceMopk90PBNClFtz2Wc2tΣkQΞΞ.Skip(bs)
}

var MyStructMUS = myStructMUS{}

type myStructMUS struct{}

func (s myStructMUS) Marshal(v struct_testdata.MyStruct, bs []byte) (n int) {
	n = unsafe.Int.Marshal(v.Int, bs)
	return n + ord.String.Marshal(v.Str, bs[n:])
}

func (s myStructMUS) Unmarshal(bs []byte) (v struct_testdata.MyStruct, n int, err error) {
	v.Int, n, err = unsafe.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	v.Str, n1, err = ord.String.Unmarshal(bs[n:])
	n += n1
	return
}

func (s myStructMUS) Size(v struct_testdata.MyStruct) (size int) {
	size = unsafe.Int.Size(v.Int)
	return size + ord.String.Size(v.Str)
}

func (s myStructMUS) Skip(bs []byte) (n int, err error) {
	n, err = unsafe.Int.Skip(bs)
	if err != nil {
		return
	}
	var n1 int
	n1, err = ord.String.Skip(bs[n:])
	n += n1
	return
}

var ComplexStructMUS = complexStructMUS{}

type complexStructMUS struct{}

func (s complexStructMUS) Marshal(v struct_testdata.ComplexStruct, bs []byte) (n int) {
	n = unsafe.Bool.Marshal(v.Bool, bs)
	n += unsafe.Uint8.Marshal(v.Byte, bs[n:])
	n += unsafe.Int8.Marshal(v.Int8, bs[n:])
	n += unsafe.Int16.Marshal(v.Int16, bs[n:])
	n += unsafe.Int32.Marshal(v.Int32, bs[n:])
	n += unsafe.Int64.Marshal(v.Int64, bs[n:])
	n += unsafe.Uint8.Marshal(v.Uint8, bs[n:])
	n += unsafe.Uint16.Marshal(v.Uint16, bs[n:])
	n += unsafe.Uint32.Marshal(v.Uint32, bs[n:])
	n += unsafe.Uint64.Marshal(v.Uint64, bs[n:])
	n += unsafe.Float32.Marshal(v.Float32, bs[n:])
	n += unsafe.Float64.Marshal(v.Float64, bs[n:])
	n += ord.String.Marshal(v.String, bs[n:])
	n += unsafe.ByteSlice.Marshal(v.ByteSlice, bs[n:])
	n += sliceZJwnVgvHlXXapX34kEBjygΞΞ.Marshal(v.StructSlice, bs[n:])
	n += arrayΣvrFYO2uuK77BSwd06iBygΞΞ.Marshal(v.Array, bs[n:])
	n += ptr0UddYOKdSqL09vDtrQX5nQΞΞ.Marshal(v.PtrString, bs[n:])
	n += ptrjoB7csTrtA9B1JLZgTz6UAΞΞ.Marshal(v.PtrStruct, bs[n:])
	n += ptr0UddYOKdSqL09vDtrQX5nQΞΞ.Marshal(v.NilPtr, bs[n:])
	n += ptrUT3ΔQ8KtGkzUdPF4EjzKUAΞΞ.Marshal(v.PtrArray, bs[n:])
	n += map71wXjOfIxEib3Yt8SxUdDgΞΞ.Marshal(v.Map, bs[n:])
	n += unsafe.TimeUnix.Marshal(v.Time, bs[n:])
	n += MySliceMUS.Marshal(v.Alias, bs[n:])
	return n + struct_testdata.MyInterfaceMUS.Marshal(v.Interface, bs[n:])
}

func (s complexStructMUS) Unmarshal(bs []byte) (v struct_testdata.ComplexStruct, n int, err error) {
	v.Bool, n, err = unsafe.Bool.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	v.Byte, n1, err = unsafe.Uint8.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Int8, n1, err = unsafe.Int8.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Int16, n1, err = unsafe.Int16.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Int32, n1, err = unsafe.Int32.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Int64, n1, err = unsafe.Int64.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint8, n1, err = unsafe.Uint8.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint16, n1, err = unsafe.Uint16.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint32, n1, err = unsafe.Uint32.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint64, n1, err = unsafe.Uint64.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Float32, n1, err = unsafe.Float32.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Float64, n1, err = unsafe.Float64.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.String, n1, err = ord.String.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.ByteSlice, n1, err = unsafe.ByteSlice.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.StructSlice, n1, err = sliceZJwnVgvHlXXapX34kEBjygΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Array, n1, err = arrayΣvrFYO2uuK77BSwd06iBygΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.PtrString, n1, err = ptr0UddYOKdSqL09vDtrQX5nQΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.PtrStruct, n1, err = ptrjoB7csTrtA9B1JLZgTz6UAΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.NilPtr, n1, err = ptr0UddYOKdSqL09vDtrQX5nQΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.PtrArray, n1, err = ptrUT3ΔQ8KtGkzUdPF4EjzKUAΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Map, n1, err = map71wXjOfIxEib3Yt8SxUdDgΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Time, n1, err = unsafe.TimeUnix.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Alias, n1, err = MySliceMUS.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Interface, n1, err = struct_testdata.MyInterfaceMUS.Unmarshal(bs[n:])
	n += n1
	return
}

func (s complexStructMUS) Size(v struct_testdata.ComplexStruct) (size int) {
	size = unsafe.Bool.Size(v.Bool)
	size += unsafe.Uint8.Size(v.Byte)
	size += unsafe.Int8.Size(v.Int8)
	size += unsafe.Int16.Size(v.Int16)
	size += unsafe.Int32.Size(v.Int32)
	size += unsafe.Int64.Size(v.Int64)
	size += unsafe.Uint8.Size(v.Uint8)
	size += unsafe.Uint16.Size(v.Uint16)
	size += unsafe.Uint32.Size(v.Uint32)
	size += unsafe.Uint64.Size(v.Uint64)
	size += unsafe.Float32.Size(v.Float32)
	size += unsafe.Float64.Size(v.Float64)
	size += ord.String.Size(v.String)
	size += unsafe.ByteSlice.Size(v.ByteSlice)
	size += sliceZJwnVgvHlXXapX34kEBjygΞΞ.Size(v.StructSlice)
	size += arrayΣvrFYO2uuK77BSwd06iBygΞΞ.Size(v.Array)
	size += ptr0UddYOKdSqL09vDtrQX5nQΞΞ.Size(v.PtrString)
	size += ptrjoB7csTrtA9B1JLZgTz6UAΞΞ.Size(v.PtrStruct)
	size += ptr0UddYOKdSqL09vDtrQX5nQΞΞ.Size(v.NilPtr)
	size += ptrUT3ΔQ8KtGkzUdPF4EjzKUAΞΞ.Size(v.PtrArray)
	size += map71wXjOfIxEib3Yt8SxUdDgΞΞ.Size(v.Map)
	size += unsafe.TimeUnix.Size(v.Time)
	size += MySliceMUS.Size(v.Alias)
	return size + struct_testdata.MyInterfaceMUS.Size(v.Interface)
}

func (s complexStructMUS) Skip(bs []byte) (n int, err error) {
	n, err = unsafe.Bool.Skip(bs)
	if err != nil {
		return
	}
	var n1 int
	n1, err = unsafe.Uint8.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int8.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int16.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int32.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int64.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint8.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint16.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint32.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint64.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Float32.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Float64.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.String.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.ByteSlice.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = sliceZJwnVgvHlXXapX34kEBjygΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = arrayΣvrFYO2uuK77BSwd06iBygΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ptr0UddYOKdSqL09vDtrQX5nQΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ptrjoB7csTrtA9B1JLZgTz6UAΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ptr0UddYOKdSqL09vDtrQX5nQΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ptrUT3ΔQ8KtGkzUdPF4EjzKUAΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = map71wXjOfIxEib3Yt8SxUdDgΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.TimeUnix.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = MySliceMUS.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = struct_testdata.MyInterfaceMUS.Skip(bs[n:])
	n += n1
	return
}
